export const STATIC_DATA = {
  TOKEN: 'D9_TOKEN',
  LOGIN: 'is_LOGIN',
  USER_NAME: 'USER_NAME',
  FULL_NAME: 'FULL_NAME',
  ROLES: 'D9_ROLES',
  USER_CURRENT: 'USER_CURRENT',
  AUTHORIZATION: 'Authorization',
  EXPIRATION: 'EXPIRATION_DATE',
};
